// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edsvbgthdecgdyykuqcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkc3ZiZ3RoZGVjZ2R5eWt1cWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NTY3MTYsImV4cCI6MjA1NjQzMjcxNn0.r-F3SSFThWURFbBvpL8jabnjxe5iRyysHDDhdU33JGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);